version: "3.8"

services:
  postgres:
    container_name: fullstack-interview-postgres
    image: postgres:16.1-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      DATABASE: fullstack_interview_dev_local
      DATABASE_TESTS: fullstack_interview_dev_tests
    volumes:
      - ./scripts/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - appnet

  frontend:
    container_name: fullstack-interview-frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
